### PR TITLE
Auto generate codes (Models, Enums and Request Builders)

### PR DESCRIPTION
**Pull request by rezigned**
~~We have to wait until #90 get merged first.~~
It's ready 🎉

### CODE REVIEW

**Comment by nuxzero** [comment]
I'll wait for solve conflicting files fixed then I'll start review this PR. 🙂

**Comment by nuxzero** [comment]
Or is there is anything to generate docs?

**Comment by rezigned** [comment]
> I think we should keep docs. Is it possible to keep docs when generate the code?
Do you mean these kind of docs?

```
/**
 * Represents Omise Bank Account object.
 *
 * @see <a href="https://www.omise.co/bank-account-api">Bank Account API</a>
 */
```

Yes, we can preserve it.

**Comment by nuxzero** [comment]
Yes, that would be great. 👍

**Pull request merged**
