### PR TITLE
 2.7.4 version upgrade

### PR DESCRIPTION
**Pull request by Namiii**
Upgrade omise-java library version from 2.7.3 to 2.7.4

(Excuse my git commit message 🤦‍♂️)

### CODE REVIEW

**Comment by pitiphong-p** [comment]
Also you can change the commit message via the `git commit --amend` command

**Comment by Namiii** [comment]
You're right, I'll change that now. Can I also change commit name that's already been pushed with amend?

**Comment by pitiphong-p** [comment]
Then you need to force push but since there should be no-one pull that yet. So I think it's fine to do that

**Comment by Namiii** [comment]
Alright great, will do that 👌

**Comment by Namiii** [comment]
All done 👍

**Pull request merged**
